name: powerswitch
base: core22
version: '0.2'
summary: Reboot or shutdown Ubuntu Core system using curl.
description: |
  This snap provides a simple set of API to reboot or shutdown an Ubuntu Core system using curl.
  To reboot, use: curl http://localhost:3500/reboot
  To shutdown, use: curl http://localhost:3500/poweroff

#grade: devel #This is for development only.
#confinement: devmode #This is for development only. Unconfined snap environment. For production, use strict.
grade: stable #This is for releasing in the stable channel.
confinement: strict #This is for production only.

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]
  - build-on: [amd64, armhf]
    build-for: [armhf]
  - build-on: [amd64, ppc64el]
    build-for: [ppc64el]
  - build-on: [amd64, s390x]
    build-for: [s390x]

apps:
  api:
    command: bin/flask-wrapper
    daemon: simple
    restart-condition: always
    plugs: [network-bind, shutdown]
    environment:
      FLASK_APP: ./api.py
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:
  #Copy the bash scripts
  bash-scripts:
    plugin: dump
    source: bin
    organize:
      pwr_mgmt: bin/

  #Install all packages from requirements
  python-packages:
    plugin: python
    source: flask
    python-requirements: ['requirements.txt']

  #Copy the flask api
  flask-server:
    plugin: dump
    source: flask
    organize:
      api.py: bin/
      flask-wrapper: bin/
